#!/bin/bash
set -e
which python2 > /dev/null

cd "$(dirname "$0")"

if [ ! -f webvirtmgr.sqlite3 ] || [ "$(stat -c%s webvirtmgr.sqlite3)" == "0" ];then
    python2 manage.py syncdb --noinput
fi
exec python2 manage.py run_gunicorn -c conf/gunicorn.conf.py